# Generated by Django 6.1.1 on 2026-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('is_known_disease', models.BooleanField(default=True)),
                ('is_banana_leaf', models.BooleanField(default=True)),
                ('heatmap', models.ImageField(blank=True, upload_to='heatmaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
